City-of-Helsinki/drupal-employment-services

- conf/cmi/core.entity_form_display.paragraph.accordion.default.yml
- conf/cmi/field.field.paragraph.accordion_item.field_accordion_item_content.yml
- public/sites/default/all.settings.php
- public/sites/default/settings.php
Remove unneeded target bundles from Accordion
Update settings.php with hel.fi updates
Add all.settings.php file for site specific settings
> THF-162: Accordion

- composer.json
- composer.lock
- conf/cmi/core.extension.yml
- public/modules/custom/tyollisyyspalvelut_common/tyollisyyspalvelut_common.module
Add helfi azure fs module to generate imagestyles on first load.
Hide preview button from node form.
Add custom redirect after node save. Redirects user to node view page.
> Add helfi azure fs module

- conf/cmi/core.entity_form_display.paragraph.events_list.default.yml
- conf/cmi/core.entity_view_display.paragraph.events_list.default.yml
- conf/cmi/field.field.paragraph.events_list.field_event_tag_filter.yml
- conf/cmi/field.field.paragraph.events_list.field_events_list_short.yml
- conf/cmi/field.storage.node.field_tags.yml
- conf/cmi/field.storage.paragraph.field_event_tag_filter.yml
- conf/cmi/field.storage.paragraph.field_events_list_short.yml
- conf/cmi/filter.format.basic_html.yml
- conf/cmi/paragraphs.paragraphs_type.events_list.yml
- conf/cmi/search_api.index.events_fi.yml
Change event tag
Add path to elastic index
Change event list fields
Remove span tag from basic html textformat
> Event related changes

- conf/cmi/search_api.index.events_fi.yml
Remove ignore case setting for some fields.
> Elastic index configs

- conf/cmi/core.entity_form_display.node.article.default.yml
- conf/cmi/pathauto.pattern.news_pattern_en.yml
- conf/cmi/pathauto.pattern.news_pattern_fi.yml
- conf/cmi/pathauto.pattern.news_pattern_sv.yml
This is the foundation for Article pages for publishing news. it is missing quotes and banners for now.
> THF-214/THF-265: setting up article type for news

- composer.json
Updated composer locally first to 2.2. version and the run composer install to allow the needed packages.
> Composer update to allow plugins.

- composer.json
- composer.lock
- Drupal core - Moderately critical - Information Disclosure - SA-CORE-2022-012 (https://www.drupal.org/sa-core-2022-012)
- Drupal core - Moderately critical - Access Bypass - SA-CORE-2022-013 (https://www.drupal.org/sa-core-2022-013)
> Drupal core security updates.

- conf/cmi/field.field.node.page.field_content.yml
Add event list to basic page's field content
> THF-300: Add event list to basic page's field content

- conf/cmi/core.entity_form_display.node.page.default.yml
- conf/cmi/core.entity_view_display.node.page.default.yml
- conf/cmi/core.entity_view_display.node.page.search_index.yml
- conf/cmi/field.field.node.page.field_hide_sidebar.yml
- conf/cmi/field.storage.node.field_hide_sidebar.yml
There's now option for hiding sidebar on Basic Page forms.
> THF-273: Adding sidebar hidding option for Basic Page

- conf/cmi/core.entity_form_display.paragraph.events_list.default.yml
- conf/cmi/core.entity_form_display.paragraph.list_of_links.default.yml
- conf/cmi/core.entity_view_display.paragraph.list_of_links.default.yml
- conf/cmi/field.field.paragraph.list_of_links.field_background_color.yml
Add background color fields for events list and list of links paragraphs
> THF-298: Add bg color fields for paragraphs

- conf/cmi/user.role.anonymous.yml
- conf/cmi/user.role.authenticated.yml
Add needed article and event permissions for authenticated user
Remove unneeded permissions from anonymous
> Change permissions

- composer.lock
Rollback composer packages that didn't work on server after update.
> Rollback composer package versions.

- conf/cmi/core.entity_form_display.paragraph.units_list.default.yml
- conf/cmi/core.entity_view_display.paragraph.units_list.default.yml
- conf/cmi/field.field.node.page.field_lower_content.yml
- conf/cmi/paragraphs.paragraphs_type.units_list.yml
- Enables TPR Units to have listing paragraph on Basic Page lower content.
> THF-168: Adding TPR Units list paragraph

- conf/cmi/field.field.tpr_unit.tpr_unit.field_content.yml
- conf/cmi/field.field.tpr_unit.tpr_unit.field_lower_content.yml
- conf/cmi/paragraphs.paragraphs_type.unit_map.yml
- New component Unit Map replacing static map embed in template
- Updated Content and Lower Content regions components selection
> THF-204: Updated Units components

- docker/openshift/crons/migrate-tpr.sh
- Updates TPR sync cron run from 6 hours to 15 minutes
> THF-321: THF-321: Added TPR sync interval to 15mins.

- composer.json
- composer.lock
- conf/cmi/core.entity_form_display.paragraph.hero.default.yml
- conf/cmi/core.entity_form_display.paragraph.image.default.yml
- conf/cmi/core.extension.yml
- conf/cmi/entity_browser.browser.image.yml
- conf/cmi/image.style.hero.yml
- conf/cmi/views.view.entity_browser.yml
- Add Focal Point module
- Add Entity Browser module for better UX on focal point edit
- Includes configuration and views
> THF-258: THF-258: Adding Focal Point module/configuration.

- composer.json
- composer.lock
- conf/cmi/next.settings.yml
How to test:
```
composer install
make shell
drush deploy
```
Edit the Next.js user and assign them all the roles that are going to be used for scopes, including the administrator role and the Next.js role. The granted roles will be filtered based on roles assigned to the current user.
This PR should be tested with this PR: https://github.com/City-of-Helsinki/employment-services-ui/pull/199
> Update next module and add configs

- conf/cmi/user.role.authenticated.yml
- Fixes permission issue on adding image to the content
> Updated access to Image pages

- public/modules/custom/tyollisyyspalvelut_common/tyollisyyspalvelut_common.services.yml
- Add override setting for internal domains.
> THF-306: THF-306: Overriding default internal domains.

- conf/cmi/pathauto.pattern.event_pattern_en.yml
- conf/cmi/pathauto.pattern.event_pattern_sv.yml
- conf/cmi/pathauto.pattern.news_pattern_en.yml
- conf/cmi/pathauto.pattern.news_pattern_fi.yml
- conf/cmi/pathauto.pattern.news_pattern_sv.yml
- Updates pathauto URL aliases for News and Events
- Requires Bulk Update for old aliases
> THF-341: Adding translated paths for News & Events.

- conf/cmi/core.extension.yml
- conf/cmi/next.next_entity_type_config.node.article.yml
- conf/cmi/next.next_entity_type_config.node.event.yml
- conf/cmi/next.next_entity_type_config.node.landing_page.yml
- conf/cmi/next.next_entity_type_config.node.news.yml
- conf/cmi/next.next_entity_type_config.node.page.yml
- conf/cmi/next.next_entity_type_config.tpr_unit.tpr_unit.yml
Enable next extras module. 
Add revalidation settings for entity types.
> THF-X: on demand revalidation

- conf/cmi/core.entity_form_display.node.event.default.yml
- conf/cmi/core.entity_view_display.node.event.default.yml
- conf/cmi/core.entity_view_display.node.event.teaser.yml
- conf/cmi/field.field.node.event.field_street_address.yml
- conf/cmi/field.storage.node.field_street_address.yml
- conf/cmi/search_api.index.events_fi.yml
- Requires Events remove and re-sync (`drush entity:delete node --bundle=event`)
> THF-330: New field for event street address info.

- conf/cmi/views.view.media.yml
- Media list now looks similar to the content list
> THF-422: Adding language column for media list.

- conf/cmi/search_api.index.articles_en.yml
- conf/cmi/search_api.index.articles_fi.yml
- conf/cmi/search_api.index.articles_sv.yml
- conf/cmi/search_api.index.events_en.yml
- conf/cmi/search_api.index.events_sv.yml
- conf/cmi/search_api.index.landings_en.yml
- conf/cmi/search_api.index.landings_fi.yml
- conf/cmi/search_api.index.landings_sv.yml
- conf/cmi/search_api.index.pages_en.yml
- conf/cmi/search_api.index.pages_fi.yml
- conf/cmi/search_api.index.pages_sv.yml
- conf/cmi/search_api.index.units_en.yml
- conf/cmi/search_api.index.units_fi.yml
- conf/cmi/search_api.index.units_sv.yml
- New site wide search for test environment
> THF-170: Adding search indices for the site content

- conf/cmi/core.extension.yml
- conf/cmi/search_api.index.articles_en.yml
- conf/cmi/search_api.index.articles_fi.yml
- conf/cmi/search_api.index.articles_sv.yml
- conf/cmi/search_api.index.events_en.yml
- conf/cmi/search_api.index.events_fi.yml
- conf/cmi/search_api.index.events_sv.yml
- conf/cmi/search_api.index.landings_en.yml
- conf/cmi/search_api.index.landings_fi.yml
- conf/cmi/search_api.index.landings_sv.yml
- conf/cmi/search_api.index.pages_en.yml
- conf/cmi/search_api.index.pages_fi.yml
- conf/cmi/search_api.index.pages_sv.yml
- conf/cmi/search_api.index.units_en.yml
- conf/cmi/search_api.index.units_fi.yml
- conf/cmi/search_api.index.units_sv.yml
- public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexMappingSubscriber.php
- public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexSubscriber.php
- public/modules/custom/tyollisyyspalvelut_elasticsearch/tyollisyyspalvelut_elasticsearch.info.yml
- public/modules/custom/tyollisyyspalvelut_elasticsearch/tyollisyyspalvelut_elasticsearch.services.yml
- Helper module for search suggestions
- HTML filters for search API indices
> THF-170: Search updates

- conf/cmi/core.entity_form_display.node.event.default.yml
- conf/cmi/core.entity_view_display.node.event.default.yml
- conf/cmi/core.entity_view_display.node.event.teaser.yml
- conf/cmi/field.field.node.event.field_event_status.yml
- conf/cmi/field.storage.node.field_event_status.yml
- conf/cmi/search_api.index.events_fi.yml
Included commits
- THF-423: Adding status field for events
> Release Jan 2023

- public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
- Fixes issue where node Title didn't update when updating node content
> THF-462: Adding Title updates during sync

- composer.json
- composer.lock
- conf/cmi/core.extension.yml
Publication date modele added to Drupal.
How to test:
- Related PR -> [THF-446-published-date-for-articles-ui](https://github.com/City-of-Helsinki/employment-services-ui/pull/280)
- `make up; make build; make post-install`
- run relaited branch with introductions THF-446-published-date-for-articles-ui
- Create new article page on Drupal [add article](https://drupal-tyollisyyspalvelut-helfi.docker.so/node/add)
- Check that article has date under page title.
- Create new article https://drupal-tyollisyyspalvelut-helfi.docker.so/node/add and scheduled publication date for next day.
- See next day that the date underneath title has changed to the publication date.
> Thf 446 published date for articles drupal

- public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexSubscriber.php
Added snowball - for testing purpose
> Thf 501 snowball pluggin

- .env
add plugging snowball testing only
> THF-501: THF-501: correct .env

- public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexMappingSubscriber.php
- public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexSubscriber.php
remove index changes from test.
> THF-501: THF-501: remove ElasticSearc index changes

- docker-compose.override.yml
Added Elasticsearch docker-compose.override.yml file to the Drupal project root.
How to test:
- `make up`
- `curl -X DELETE http://localhost:9200/\*_fi `
- `curl -X DELETE http://localhost:9200/\*_en`
- `curl -X DELETE http://localhost:9200/\*_sv`
- `make shell`
- `drush search-api:clear`
- `drush sapi-rt`
-  `drush sapi-i`
After you have run all command try search and event page that they works as before.
> Thf 501 local Elasticsearch

- conf/cmi/core.entity_form_display.node.event.default.yml
- conf/cmi/core.entity_view_display.node.event.default.yml
- conf/cmi/core.entity_view_display.node.event.teaser.yml
- conf/cmi/field.field.node.event.field_provider.yml
- conf/cmi/field.field.node.event.field_publisher.yml
- conf/cmi/field.storage.node.field_provider.yml
- public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
Added field provider and handling for field publisher
- Test with branch  https://github.com/City-of-Helsinki/employment-services-ui/pull/349
```
drush edel node --bundle=event
drush linkedevents:sync
drush sapi-rt
drush sapi-i
```
- See that you don't get errors
Finnish testing in branch https://github.com/City-of-Helsinki/employment-services-ui/pull/349
> THF-534: THF-534: Add field provider and publisher

- public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexMappingSubscriber.php
- public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexSubscriber.php
Added snowball plugging to handler better Finnish language search.
- run commands ` drush search-api:clear; drush search-api:rebuild-tracker; drush search-api:index; drush cr;`
- Try if the search works better than in production. 
- Try example words kotoutumiskoulutuksen ja kotoutumis koulutus
> THF-501: THF-501: Add snowball

- conf/cmi/search_api.index.events_en.yml
- conf/cmi/search_api.index.events_fi.yml
- conf/cmi/search_api.index.events_sv.yml
- public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
Added field_in_language field to APiSearch
-test with https://github.com/City-of-Helsinki/employment-services-ui/pull/365
> THF-594: THF-594: Add in_language to api search
