conf/cmi/user.role.anonymous.yml
Assign the Issue subrequests permission to the Anonymous user role:
We do this because during the build phase, most of the requests for pages are anonymous requests. By assigning this permission, you can significantly decrease your site's build time.
https://next-drupal.org/docs/upgrade-guide
=> Add permission configs

conf/cmi/metatag.metatag_defaults.node.yml
- Use `Lead-in` field as default for description.
- Site name to the title comes from NextJS
=> THF-182: THF-182: Updated default metatag tokens.

conf/cmi/pathauto.pattern.event_pattern.yml
- Path alias updates to make the breadcrumb working for Events
- Includes Finnish language only
- Requires bulk update for path aliases
- May require re-indexing Elasticsearch
=> THF-299: Updated Events pathalias to match breadcrumb structure

conf/cmi/jsonapi_extras.jsonapi_resource_config.paragraph--accordion.yml, conf/cmi/jsonapi_extras.jsonapi_resource_config.paragraph--banner.yml, conf/cmi/jsonapi_extras.jsonapi_resource_config.paragraph--events_list.yml, conf/cmi/jsonapi_extras.jsonapi_resource_config.paragraph--liftup_with_image.yml, conf/cmi/jsonapi_extras.jsonapi_resource_config.paragraph--news_list.yml, conf/cmi/jsonapi_extras.jsonapi_resource_config.paragraph--notification.yml, public/modules/custom/tyollisyyspalvelut_common/src/Plugin/jsonapi/FieldEnhancer/TextFieldEnhancer.php
Add JSON:API text field enhancer plugin for changing internal node links to URL aliases in text fields.
Add field enhancer for needed fields in JSON:API
**How to test**
```
git checkout
drush cim
drush cr
```
Check that links that showed previously /node/1234 url show now url alias. Example links can be found from here: https://helsinkisolutionoffice.atlassian.net/browse/THF-320?atlOrigin=eyJpIjoiMWFiNTkzOTBkYmVlNDc1MGI1NWExYWIyOTA5NWVkMWEiLCJwIjoiaiJ9
=> THF-32: broken node links

conf/cmi/editor.editor.basic_html.yml, public/modules/custom/tyollisyyspalvelut_common/css/ckeditor.css
Changed ckEditor to use tpr_content as link profile and added styling to data-entity-type="tpr_unit" as it is with data-entity-type="node". It should follow the same roles as internall node links.
How to test:
start ui with the project `THF-468-TPR-links-ui`
- `make shell`
- `drush cim -y`
- `drush cr`
- Create new basic page and add text paragraph
- Add link to the editor with some office, example kamppi https://drupal-tyollisyyspalvelut-helfi.docker.so/node/add/page
- Link should have arrow after the link text in the ckEditor
=> THF-468: THF-468: change to tpr_content

public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
linked even sync didn't work on develop environment because tag handling tried to push array to a string field when the event tag is internet. 
This produced the following error `error: array_push() argument #1 ($array) must be of type array`
How to test:
Run also Next app with branch https://github.com/City-of-Helsinki/employment-services-ui/pull/287
- `make shell`
- `make drush cim -y`
- `make composer install`
-  remove all events `drush edel node --bundle=event` . This is important step to do to make sure you will get needed internet tag to the json.
- check from Drupal that you don't have any events. https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/content?title=&type=event&status=All&langcode=All
- Note you will get following error on local database [error] …
=> Thf 470 linked event tag internet handling

conf/cmi/core.entity_form_display.node.event.default.yml, conf/cmi/core.entity_view_display.node.event.default.yml, conf/cmi/core.entity_view_display.node.event.teaser.yml, conf/cmi/field.field.node.event.field_offers_info_url.yml, conf/cmi/field.storage.node.field_offers_info_url.yml, public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
Created field_offers_info_url to bring event sing up url from linked event. The offers info url is inside of an array. So we loop the offers to get the url. 
How to test:
This branch need to be tested with branch  https://github.com/City-of-Helsinki/employment-services-ui/pull/290
- `make shell`
- `composer install`
- `drush cim -y; drush cr;`
- sync event`drush linkedevents:sync`
- index event`drush search-api:index`
- go to drupal that you have https://drupal-tyollisyyspalvelut-helfi.docker.so/ajankohtaista/tapahtumat/testitapahtuma 
- The event should have button sing up in ui and it should have new field field_offers_info_url
=> Thf 416 linked events info url drupal

conf/cmi/core.base_field_override.node.event.title.yml, conf/cmi/core.entity_form_display.node.event.default.yml, conf/cmi/core.entity_form_display.taxonomy_term.event_tags.default.yml, conf/cmi/core.entity_view_display.node.event.default.yml, conf/cmi/core.entity_view_display.node.event.teaser.yml, conf/cmi/core.entity_view_display.taxonomy_term.event_tags.default.yml, conf/cmi/field.field.node.event.field_event_tags.yml, conf/cmi/field.field.node.event.field_in_language.yml, conf/cmi/field.field.node.event.field_info_url.yml, conf/cmi/field.field.node.event.field_location.yml, conf/cmi/field.field.node.event.field_location_extra_info.yml, conf/cmi/field.field.node.event.field_offers_info_url.yml, conf/cmi/field.field.node.event.field_short_description.yml, conf/cmi/field.field.node.event.field_street_address.yml, conf/cmi/field.field.node.event.field_text.yml, conf/cmi/field.field.taxonomy_term.event_tags.field_id.yml, conf/cmi/field.storage.node.field_event_tags.yml, conf/cmi/field.storage.taxonomy_term.field_id.yml, conf/cmi/language.content_settings.taxonomy_term.event_tags.yml, conf/cmi/search_api.index.events_en.yml, conf/cmi/search_api.index.events_fi.yml, conf/cmi/search_api.index.events_sv.yml, conf/cmi/taxonomy.vocabulary.event_tags.yml, public/modules/custom/tyollisyyspalvelut_common/tyollisyyspalvelut_common.module, public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
This PR adds language support (english and swedish) to the LinkedEvents integration.
**To test**
* Checkout branch
* Run `make drush-cr drush-cim`
* Log in to the container by running `make shell` and then run:
* `drush edel node --bundle=event`
* `drush linkedevents:sync -v`
* `drush sapi-rt;drush sapi-i`
* Check a few events and make sure they have translated data: https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/content?title=&type=event&status=All&langcode=All
* The event content itself is probably not translated, but the event location should be
* Check that the content in the new event tags taxonomy term field matches the old tags field
* Check that the event tag terms have been populated and that each tag has translations: …
=> THF-105: LinkedEvents translation support

conf/cmi/core.entity_form_display.node.landing_page.default.yml, conf/cmi/core.entity_form_display.node.page.default.yml, conf/cmi/core.entity_view_display.node.landing_page.default.yml, conf/cmi/core.entity_view_display.node.page.default.yml, conf/cmi/core.entity_view_display.node.page.search_index.yml, conf/cmi/field.field.node.landing_page.field_hide_navigation.yml, conf/cmi/field.field.node.page.field_hide_navigation.yml, conf/cmi/field.storage.node.field_hide_navigation.yml
Added possibility to hide nav from basic and landing page. Added boolean filed hide_navigation to page basic and landing. This is not ready for production. Client might need changes to the pages.
How to test:
- test with related branch https://github.com/City-of-Helsinki/employment-services-ui/pull/306
- 'make drush-cim; Make drush cr;'
- Create a landing page and switch the Hide navigation field on.
- You should get the page without nav.
- Create a basic page switch the Hide navigation field on.
- You should get the page without nav.
- The pages should be exactly same as they are in "normal" basic and landing pages.
=> Thf 493 foreign language page templates

composer.json, composer.lock, conf/cmi/filter.format.basic_html.yml, conf/cmi/filter.format.plain_text.yml, conf/cmi/filter.format.restricted_html.yml
**To test**
- Checkout branch
- Run `make up;make shell` and then `composer install;drush updb -y;drush cim -y`
- Click around on the site and make sure content editing and adding node and TPR links through the linkit modal works.
=> THF-0: Drupal updates for 26.4.2023

conf/cmi/core.entity_form_display.node.article.default.yml, conf/cmi/core.entity_form_display.paragraph.news_list.default.yml, conf/cmi/core.entity_view_display.node.article.default.yml, conf/cmi/core.entity_view_display.paragraph.news_list.default.yml, conf/cmi/field.field.node.article.field_article_category.yml, conf/cmi/field.field.node.article.field_content.yml, conf/cmi/field.field.paragraph.news_list.field_news_filter.yml, conf/cmi/field.storage.node.field_article_category.yml, conf/cmi/field.storage.paragraph.field_news_filter.yml, conf/cmi/language/fi/field.field.node.article.field_article_category.yml, conf/cmi/language/fi/field.storage.node.field_article_category.yml, conf/cmi/search_api.index.articles_en.yml, conf/cmi/search_api.index.articles_fi.yml, conf/cmi/search_api.index.articles_sv.yml, public/modules/custom/tyollisyyspalvelut_common/tyollisyyspalvelut_common.module
This PR:
- Adds missing paragraph components to articles
- Adds an article category field to differentiate between news and newsletters
- Customizes URL aliases for newsletter articles
**To test**
- Checkout branch, run `make drush-cim drush-cr`
- Also checkout and install this UI branch: https://github.com/City-of-Helsinki/employment-services-ui/pull/322
- Edit all article nodes and select the "news" article type: https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/content
- When you edit the articles, the URL alias should stay the same (`/ajankohtaista/uutiset/article-title*`) 
- Create a few new articles and select the "newsletter" article type: https://drupal-tyollisyyspalvelut-helfi.docker.so/node/add/article
- This time the URL should be something like …
=> THF-488: Newsletter content functionality for article pages

conf/cmi/system.menu.menu-other-languages.yml
Add menu for other languages.
how to test:
- `make drush-cim drush-cr`
- We should now have menu `Menu (other languages)` on page https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/structure/menu
=> THF-523: THF-523: Add menu for other languages

conf/cmi/automated_cron.settings.yml, conf/cmi/core.entity_form_display.node.article.default.yml, conf/cmi/system.date.yml, conf/cmi/user.role.authenticated.yml
Enabled scheduler and change cron run to run every hour. (before every 3 hours). Also users can not change timezone anymore from the user section. 
How to test
- Test this branch with branch https://github.com/City-of-Helsinki/employment-services-ui/compare/develop...THF-572-scheduler-ui?expand=1
- `drush cim -y; drush cr;`
- Create an article and publish it. You should have published article
- Create again a new article and schedule the publishing 2 min later.
- Wait about 3 min and run cron run https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/config/system/cron
- The article should be now published. 
- Check also that the cron run is updated to run every hour.
- Go to https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/people
- Go edit some user. You shouldn't have option to …
=> THF-572: THF-572: Change Cron run every hour

conf/cmi/core.entity_form_display.node.article.default.yml, conf/cmi/core.entity_form_display.paragraph.liftup_with_image.default.yml, conf/cmi/core.entity_view_display.paragraph.liftup_with_image.default.yml, conf/cmi/field.field.node.page.field_content.yml, conf/cmi/field.storage.node.field_article_category.yml, conf/cmi/field.storage.paragraph.field_news_filter.yml
Added new filter to paragrah News List, new category to article category and News list paragraph to Basic page.
how to test
- test with UI branch https://github.com/City-of-Helsinki/employment-services-ui/pull/343
- `make shell;`
- `drush cim -y; drush cr;`
-  Create few articles with Article category "Jobs offered by partners"
- Add News list to https://drupal-tyollisyyspalvelut-helfi.docker.so/tyonhaku/tuetut-tyopaikat/palkkatuki/kumppanien-tarjoamat-tyopaikat
- You should now see list of news that you just created (max 4) on partner job page.
- Test also that if you change the filter fo the news list you get correct news on the list.
=> THF-562: THF-562: Add partner_job filer

conf/cmi/views.view.event_content.yml
Added view Events to the content admin page. Then Event view contains only event content types. Event types are now removed from Content view.
- `Drush cim -y`
- Go to /admin/content page
- You should see new tab Events on the page
- Go to the view
- In the view you should have 
--> event type content 
--> you should not be able to filter the content by type.
- In old Content tab you should have
--> other content types Basic pages, Landing page and articles.
--> you should be able to filter by content type with Basic pages, 
Landing page and articles
=> Thf 586 Event view

conf/cmi/views.view.event_content.yml, public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
**To test**
- Checkout branch, run `make drush-cim drush-cr`
- Check the events content list: https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/content/event
- The "ID" field should be visible in the table and as a filter
- Edit an event node and change the ID to something that doesn't match a real event ID
- Run the linkedevents sync command: `drush linkedevents:sync`
- The event you modified should now be unpublished
- Read code changes
=> THF-529: Handle duplicate and removed events

conf/cmi/core.entity_form_display.node.event.default.yml, conf/cmi/core.entity_view_display.node.event.default.yml, conf/cmi/core.entity_view_display.node.event.teaser.yml, conf/cmi/field.field.node.event.field_super_event.yml, conf/cmi/field.storage.node.field_super_event.yml, public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
Added field super event
- run with branch `THF-535-super-event-ui`
- `make drush-cim; drush-cr;`
- Check from Drupal site that the Event content type has field field_super_event
- `make shell`
- `drush edel node --bundle=event`
-  `drush sapi-i`
- `drush sapi-rt`
- `drush linkedevents:sync; `
-  If the event has super_event you should have the super_event url in the super_event field- All languages
- Check that you don't get errors to the console.
- Check the code.
=> THF-535: add field super event

conf/cmi/core.entity_form_display.node.event.default.yml, conf/cmi/core.entity_form_display.taxonomy_term.event_languages.default.yml, conf/cmi/core.entity_view_display.taxonomy_term.event_languages.default.yml, conf/cmi/field.field.node.event.field_in_language.yml, conf/cmi/field.field.taxonomy_term.event_languages.field_language_id.yml, conf/cmi/field.storage.node.field_in_language.yml, conf/cmi/field.storage.taxonomy_term.field_language_id.yml, conf/cmi/language.content_settings.taxonomy_term.event_languages.yml, conf/cmi/taxonomy.vocabulary.event_languages.yml, public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexMappingSubscriber.php, public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexSubscriber.php, public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
Added handling to in_languages field.  field_in_language was existing string field in Drupal. The field is now changed to entity reverence (taxonomy).
- Test with branch https://github.com/City-of-Helsinki/employment-services-ui/pull/348
- `drush edel node --bundle=event`
-  `drush linkedevents:sync`
- `drush sapi-rt`
-  `drush sapi-i`
-  Check that you have new taxonomy terms [terms](https://drupal-tyollisyyspalvelut-helfi.docker.so/sv/admin/structure/taxonomy/manage/event_languages/overview)
- Check also that translation are in place (in this case all Finnish) 
- run commands above again and check that you don't have duplicate terms
- After running commands move to the PR https://github.com/City-of-Helsinki/employment-services-ui/pull/348
=> THF-533: THF-533: Add in_language handling

public/modules/custom/tyollisyyspalvelut_linkedevents/src/Commands/SyncContent.php
- immigrants and young people tags are coming 2 times
- sync not working.
- Check the events content list: https://drupal-tyollisyyspalvelut-helfi.docker.so/admin/content/event
- The "ID" field should be visible in the table and as a filter
- Edit an event node and change the ID to something that doesn't match a real event ID
- Run the linkedevents sync command: drush linkedevents:sync
- you should now get any errors
- The event you modified should now be unpublished
- Read code changes
- drush edel node --bundle=event
- drush linkedevents:sync
- drush search-api:clear; drush search-api:rebuild-tracker; drush search-api:index; drush cr;
- check on event page that you don't have any events which have 2 times immigrants or young people tag.
=> THF-618: fix duple tags and node null

public/modules/custom/tyollisyyspalvelut_common/tyollisyyspalvelut_common.module
Hero field is disabled from basic page. But some reason Drupal brings` #states` for `field_hero` even if I completely delete the hero fields from Drupal. 
{ ["#states"]=> array(1) { ["visible"]=> array(1) { [":input[name="field_has_hero[value]"]"]=> array(1) { ["checked"]=> bool(true) } } } }
We make hook_form_alter and empty the states if the field doesn't have '#type'
=> DRAFT: THF-567: fix disabled hero field from visibility

conf/cmi/search_api.index.articles_en.yml, conf/cmi/search_api.index.articles_fi.yml, conf/cmi/search_api.index.articles_sv.yml, conf/cmi/search_api.index.events_en.yml, conf/cmi/search_api.index.events_fi.yml, conf/cmi/search_api.index.events_sv.yml, docker-compose.override.yml, public/modules/custom/tyollisyyspalvelut_elasticsearch/src/EventSubscriber/PrepareIndexSubscriber.php
Updated Elasticsearch to version 8.4.0.
Added new fields to the Elasticsearch index.
-` make up`
- `make drush-cim`
-` make drush-cr`.
- Verify that the running Elasticsearch container is now using version 8.4.0.
- Remove the old Elasticsearch container:
- Find the old container IDs with `docker ps -a`.
- Delete a container with `docker rm <container_id>`.
- List images with `docker images`.
- Delete old Elasticsearch images using `docker rmi <image_id>`.
- Rebuild the Elasticsearch index.
```
drush search-api:clear
drush search-api:rebuild-tracker
drush search-api:index
drush cr
UI Branch 
```Check:
Check the changes in the code and then move to the UI branch: https://github.com/City-of-Helsinki/employment-services-ui/pull/381
=> Thf 622 short news event index
